num_process: 4
num_case_limit: 512
scoreboard_testcases: 150
dataset_dir: "sample_input"

print_columns:
  - score

optuna_num_trials: 20

# Google Sheets に出力したい場合
# google_sheets_exporter:
#   gcp_sa_path: "path/to/gcp_credential.json"
#   sheet_key: "***"
