num_process: 4
num_case_limit: 512
scoreboard_testcases: 50
dataset_dir: "in"

# print_columns:
#   - score

runner:
  run_comand: "cat {INPUT_FILE} | {SOLVER_CMD} 2> {SOLVER_OUTPUT}"
  # run_command: "target/release/tester {SOLVER_CMD} < {INPUT_FILE} > {SOLVER_OUTPUT} 2>&1  | sed 's/\(.*\)/{\"score\": \\1}/'"

# optuna:
#   num_trials: 20
#   sqlite_db_path: "train.db"

# Google Sheets に出力したい場合
# google_sheets:
#   gcp_sa_path: "path/to/gcp_credential.json"
#   sheet_key: "***"
